<?php
function tiddly_node_info() {
  return array(
    'tiddlywiki' => array(
      'name' => t('Tiddly Wiki'),
      'module' => 'tiddly',
      'description' => t("An entire Tiddly Wiki in a node"),
      'has_body' => FALSE,
      )
    );
    
}

function tiddly_save() {
  drupal_set_message(__FUNCTION__);
}

function tiddly_load(&$node) {
}

function tiddly_view($node, $teaser = FALSE, $page = FALSE) {
  $node->content['tiddly'] = array(
    '#weight' => -10,
    '#value' => tiddly_empty(),
  );
 
  return $node;
}


function tiddly_empty() {
  return file_get_contents(drupal_get_path('module', 'tiddly') . '/empty.html');
}

