<?php

/**
 * Implementation of hook_perm()
 *
 */
function cat_profile_perm() {
  // Magic permission to grant if a role is to always have all permissions
  return array('always have all permissions');
}

/**
 * Implementation of hook_user()
 *
 * If the user has a role that has the above-defined permission, they will be (re)granted all
 * known permissions. This effectively makes them a "user 1".
 *
 */
function cat_profile_user($op, &$edit, &$account, $category = null) {
  if ($op == 'login') {
    $users_roles = user_roles(true, 'always have all permissions');
    module_load_include('inc', 'cat_profile');
    foreach ($users_roles as $role) {
      _site_profile_role_ensure_all_perms($role);
    }
  }
}

/**
 * Implementation of hook_menu()
 */
function cat_profile_menu() {
  return array(
    'admin/reports/cat-profile-dump' => array(
      'access arguments' => array('administer site configuration'),
      'title' => 'Dump site variable(s)',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cat_profile_var_dump_form'),
      'file' => 'cat_profile.inc'
    )
  );
}

/**
 * Implementation of hook_imagecache_default_presets
 *
 * @deprecated features supports imagecache settings.
 */
function cat_profile_imagecache_default_presets() {
  module_load_include('inc', 'cat_profile');
  return _cat_profile_imagecache_default_presets();
}

/**
 * Implementation of hook_features_api().
 * @author Josh Waihi <josh@catalyst.net.nz>
 */
function cat_profile_features_api() {
  return array(
    'cat_profile_roles' => array(
      'name' => t('Roles'),
      'default_hook' => 'cat_profile_perms',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'default_filename' => 'features.cat_profile.inc',
      'file' => drupal_get_path('module', 'cat_profile') .'/cat_profile.features.inc',
    ),
    'cat_profile_workflow' => array(
      'name' => t('Workflow'),
      'default_hook' => 'cat_profile_workflow_data',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'default_filename' => 'features.cat_profile.inc',
      'file' => drupal_get_path('module', 'cat_profile') .'/cat_profile.features.inc',
    ),
    'cat_profile_blocks' => array(
      'name' => t('Blocks'),
      'default_hook' => 'cat_profile_blocks',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'file' => drupal_get_path('module', 'cat_profile') .'/cat_profile.features.inc',
    ),
    'cat_profile_messaging' => array(
      'name' => t('Messaging'),
      'default_hook' => 'cat_profile_messaging',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'file' => drupal_get_path('module', 'cat_profile') .'/cat_profile.features.inc',
    ),
  );
}
